logging:
  level: INFO
  loggers:
    honstain: DEBUG
  appenders:
    - type: file
      threshold: ERROR
      currentLogFilename: ./logs/inventory_ERROR_json.log
      archivedLogFilenamePattern: ./logs/inventory_ERROR_json-%d.log.gz
      archivedFileCount: 5
    - type: file
      threshold: DEBUG
      filterFactories:
        - type: less-than-errors
      layout:
        type: json
        flattenMdc: true
      currentLogFilename: ./logs/inventory_json.log
      archivedLogFilenamePattern: ./logs/inventory_json-%d.log.gz
      archivedFileCount: 5
    - type: console


# Setup initial configuration following Dropwizard docs - dropped HTTPS and certs
# https://www.dropwizard.io/en/latest/manual/configuration.html#default
server:
  minThreads: 20
  maxThreads: 20 # Setting this super low to help me explore the system under resource constraints
  adminMinThreads: 1
  adminMaxThreads: 4
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 7080
  adminConnectors:
    - type: http
      port: 7081
  requestLog:
    appenders:
      - type: file
        threshold: ALL
        logFormat:  "%h %l %u [%date{ISO8601}] %I '%r' %s %b '%i{Referer}' '%i{User-Agent}' %D"
        #logFormat:  "%h %l %u [%t] '%r' %s %b '%i{Referer}' '%i{User-Agent}' %D"
        #logFormat: '%h [%date{ISO8601}] "%r" %s %b %D [%i{User-Agent}]'
        currentLogFilename: ./logs/request.log
        archivedLogFilenamePattern: ./logs/request-%d.log.gz
        archivedFileCount: 5

# I have been experimenting some with the default Dropwizard use of Apache HttpClient but
# haven't decided on how I want to use it or how best to configure it, seems like the defaults
# are pretty good for experimenting on local dev environment.
# https://www.dropwizard.io/en/latest/manual/client.html
# https://www.dropwizard.io/en/latest/manual/configuration.html#man-configuration-clients-http
#httpClient:
#  timeout: 500ms
#  connectionTimeout: 500ms
#  timeToLive: 1h
#  cookiesEnabled: false
#  maxConnections: 1024
#  maxConnectionsPerRoute: 1024
#  keepAlive: 0ms
#  retries: 0
#  userAgent: KotlinInventoryService(KotlinProductService)

jerseyClient: # Remember that JerseyClient extends the attributes of httpClient
  timeout: 1000ms
  minThreads: 20
  maxThreads: 20
  workQueueSize: 8

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: InventoryService.1
      transport: tcp
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 5 second
