{
 "title": "Dropwziard Inventory",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HttpClientConnectionManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "InventoryService.*.org.apache.http.conn.HttpClientConnectionManager.KotlinInventoryService.*"
    }
   ]
  },
  {
   "title": "jersey-client-KotlinInventoryService",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "InventoryService.*.jersey-client-KotlinInventoryService.*.count"
    }
   ]
  },
  {
   "title": "client get-request COUNT rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "derivative(InventoryService.*.org.apache.http.client.HttpClient.KotlinInventoryService.get-requests.count)"
    }
   ]
  },
  {
   "title": "client get-request p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "InventoryService.*.org.apache.http.client.HttpClient.KotlinInventoryService.get-requests.p99"
    }
   ]
  },
  {
   "title": "client SocketTimeout COUNT rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "derivative(InventoryService.*.org.apache.http.client.HttpClient.KotlinInventoryService.SocketTimeoutException.count)"
    }
   ]
  },
  {
   "title": "client SocketTimeout mean_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "InventoryService.*.org.apache.http.client.HttpClient.KotlinInventoryService.SocketTimeoutException.mean_rate"
    }
   ]
  },
  { "title": "Jetty", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization"
    }
   ]
  },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.size"
    }
   ]
  },
  {
   "title": "Job Queue Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs-queue-utilization"
    }
   ]
  },
  {
   "title": "Utilization Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization-max"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "MustableServletContextHandler request count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "target": "derivative(InventoryService.*.io.dropwizard.jetty.MutableServletContextHandler.requests.count)"
    },
    {
     "target": "derivative(InventoryService.*.io.dropwizard.jetty.MutableServletContextHandler.5xx-responses.count)"
    }
   ]
  },
  {
   "title": "MustableServletContextHandler request M1 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "target": "InventoryService.*.io.dropwizard.jetty.MutableServletContextHandler.requests.m1_rate"
    }
   ]
  },
  {
   "title": "InventoryResource Total P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "InventoryService.*.honstain.InventoryResource.*.total.p99"
    }
   ]
  },
  {
   "title": "InventoryResource Total P50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "InventoryService.*.honstain.InventoryResource.*.total.p50"
    }
   ]
  },
  {
   "title": "InventoryResource Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "target": "derivative(InventoryService.*.honstain.InventoryResource.*.total.count)"
    }
   ]
  },
  { "title": "HttoConnectionFactory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "HttpConnectionFactory Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "target": "derivative(InventoryService.*.org.eclipse.jetty.server.HttpConnectionFactory.7080.connections.count)"
    }
   ]
  },
  {
   "title": "HttpConnectionFactory Connection Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "InventoryService.*.org.eclipse.jetty.server.HttpConnectionFactory.7080.connections.mean"
    }
   ]
  }
 ]
}